- name: Install nodejs
  include_role:
    name: common
    tasks_from: nodejs

- name: Download the package from github
  include_role:
    name: common
    tasks_from: systemd
  vars:
    APP_DIR: /tmp/user-main
    EXTRACT_DIR: /tmp

#- name: Copy SystemD file
#  copy:
#    src: systemd.service
#    dest: /etc/systemd/system/{{COMPONENT}}.service
#
#- name: Start user
#  systemd:
#    name: user
#    enabled: yes
#    state: started
#    daemon_reload: yes