help:
		@echo


frontend:
		@sh components/frontend.sh

mongodb:
		@sh components/mongodb.sh

cart:
		@sh components/cart.sh

mysql:
		@sh components/mysql.sh

catalogue:
		@sh components/catalogue.sh

payments:
		@sh components/payments.sh

rabbitmq:
		@sh components/rabbitmq.sh

redis:
		@sh components/redis.sh

shipping:
		@sh components/shipping.sh

user:
		@sh components/user.sh