help:
    @echo


frontend:
    @sh components/frontend.sh
mongodb:
    @sh components/mongodb.sh
catalogue:
    @sh components/catalogue.sh
redis:
    @sh components/redis.sh
user:
    @sh components/redis.sh
cart:
    @sh components/cart.sh
mysql:
    @sh components/mysql.sh
shipping:
    @sh components/shipping.sh
rabbitmq:
    @sh components/rabbitmq.sh
payments:
    @sh components/payments.sh

